upstream app_backend {
    server app_server:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Time to open the TCP connection
        proxy_connect_timeout 2s;
        # Time to send the request data to the backend, after the connection has been established
        proxy_send_timeout 5s;
        # Time to wait for the answer from the server
        proxy_read_timeout 5s;

        # Intercept errors to show the maintenance page
        proxy_intercept_errors on;
        error_page 502 503 504 /error.html;
    }

    location = /error.html {
        root /usr/share/nginx/html;
        internal;
    }
}
